weapons = [
    [1, "Desert Eagle", "weapon_deagle", "pistol"],
    [2, "Dual Berettas", "weapon_elite", "pistol"],
    [3, "Five-SeveN", "weapon_fiveseven", "pistol"],
    [4, "Glock-18", "weapon_glock", "pistol"],
    [30, "Tec-9", "weapon_tec9", "pistol"],
    [32, "P2000", "weapon_hkp2000", "pistol"],
    [36, "P250", "weapon_p250", "pistol"],
    [61, "USP-S", "weapon_usp_silencer", "pistol"],
    [63, "CZ75-Auto", "weapon_cz75a", "pistol"],
    [64, "R8 Revolver", "weapon_revolver", "pistol"],

    [17, "MAC-10", "weapon_mac10", "smg"],
    [19, "P90", "weapon_p90", "smg"],
    [23, "MP5-SD", "weapon_mp5sd", "smg"],
    [24, "UMP-45", "weapon_ump45", "smg"],
    [26, "PP-Bizon", "weapon_bizon", "smg"],
    [33, "MP7", "weapon_mp7", "smg"],
    [34, "MP9", "weapon_mp9", "smg"],

    [7, "AK-47", "weapon_ak47", "rifle"],
    [8, "AUG", "weapon_aug", "rifle"],
    [10, "FAMAS", "weapon_famas", "rifle"],
    [13, "Galil AR", "weapon_galilar", "rifle"],
    [16, "M4A4", "weapon_m4a4", "rifle"],
    [39, "SG 553", "weapon_sg556", "rifle"],
    [60, "M4A1-S", "weapon_m4a1_silencer", "rifle"],

    [9, "AWP", "weapon_awp", "sniper"],
    [11, "G3SG1", "weapon_g3sg1", "sniper"],
    [38, "SCAR-20", "weapon_scar20", "sniper"],
    [40, "SSG 08", "weapon_ssg08", "sniper"],

    [14, "M249", "weapon_m249", "heavy"],
    [25, "XM1014", "weapon_xm1014", "heavy"],
    [27, "MAG-7", "weapon_mag7", "heavy"],
    [28, "Negev", "weapon_negev", "heavy"],
    [29, "Sawed-Off", "weapon_sawedoff", "heavy"],
    [35, "Nova", "weapon_nova", "heavy"],

    [31, "Zeus x27", "weapon_taser", "equipment"],

    [500, "Bayonet", "weapon_bayonet", "knife"],
    [503, "Classic Knife", "weapon_knife_css", "knife"],
    [505, "Flip Knife", "weapon_knife_flip", "knife"],
    [506, "Gut Knife", "weapon_knife_gut", "knife"],
    [507, "Karambit", "weapon_knife_karambit", "knife"],
    [508, "M9 Bayonet", "weapon_knife_m9_bayonet", "knife"],
    [509, "Huntsman Knife", "weapon_knife_tactical", "knife"],
    [512, "Falchion Knife", "weapon_knife_falchion", "knife"],
    [514, "Bowie Knife", "weapon_knife_survival_bowie", "knife"],
    [515, "Butterfly Knife", "weapon_knife_butterfly", "knife"],
    [516, "Shadow Daggers", "weapon_knife_push", "knife"],
    [517, "Paracord Knife", "weapon_knife_cord", "knife"],
    [518, "Survival Knife", "weapon_knife_canis", "knife"],
    [519, "Ursus Knife", "weapon_knife_ursus", "knife"],
    [520, "Navaja Knife", "weapon_knife_gypsy_jackknife", "knife"],
    [521, "Nomad Knife", "weapon_knife_outdoor", "knife"],
    [522, "Stiletto Knife", "weapon_knife_stiletto", "knife"],
    [523, "Talon Knife", "weapon_knife_widowmaker", "knife"],
    [525, "Skeleton Knife", "weapon_knife_skeleton", "knife"]
]